service mysql start;
mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH 'mysql_native_password' BY '${SQL_RPASS}';";
mysql -e "DELETE FROM mysql.user WHERE User = '';";
mysql -e "DELETE FROM mysql.user WHERE User = 'root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');";
mysql -e "FLUSH PRIVILEGES;";
mysql -e "DROP DATABASE IF EXISTS test;";
mysql -e "CREATE DATABASE IF NOT EXISTS \`${SQL_DB}\`;";
mysql -e "CREATE USER IF NOT EXISTS \`${SQL_USER}\`@'%' IDENTIFIED WITH 'mysql_native_password' BY '${SQL_PASS}';";
mysql -e "GRANT SELECT, INSERT, UPDATE, DELETE, ALTER, CREATE TABLE, DROP TABLE, INDEX ON \`${SQL_DB}\`.* TO \`${SQL_USER}\`@'%';";
mysql -e "FLUSH PRIVILEGES;";
